name: Automated data update

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Scrape and build data
      uses: actions/setup-python@v1
      with:
        python-version: '3.8.6'
        architecture: x64

    - run: |
        pip install pandas requests lxml
        python GsscFlowV.0.3.py

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit --allow-empty -m "Automated Publicly Available Gas Data" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
